name: Publish packages to NPM Package Registry

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
          scope: "@rikvermeulen"

      - name: Check if @rikvermeulen/middlewares-robots-txt version has been updated
        id: robotsTxt
        uses: EndBug/version-check@v1
        with:
          diff-search: true
          file-name: robots-txt/package.json
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish @rikvermeulen/middlewares-robots-txt
        if: steps.robotsTxt.outputs.changed == 'true'
        run: npm publish robots-txt --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
